/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import entidades.Ingrediente;
import javax.swing.text.AbstractDocument;
import utils.SoloFiltroNumerico;

/**
 *
 * @author janot
 */
public class VentanaDecrementarStockIngrediente extends javax.swing.JDialog {

    /**
     * Creates new form VentanaDecrementarStockIngrediente
     */
    public VentanaDecrementarStockIngrediente(VentanaIngredientes ventana, boolean modal, Ingrediente ingrediente) {
        super(ventana, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDecrementar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jTextFieldDecrementar = new javax.swing.JTextField();
        jPanelMesero = new GUI.PanelRound();
        jLabelAceptar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDecrementar.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelDecrementar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDecrementar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDecrementar.setText("Decrementar:");
        jPanel1.add(jLabelDecrementar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, -1));

        jLabel2.setFont(new java.awt.Font("Product Sans Infanity", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Decrementar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 160, -1));

        jLabelStock.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelStock.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelStock.setText("Stock:");
        jPanel1.add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 210, -1));

        jTextFieldDecrementar.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDecrementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDecrementarActionPerformed(evt);
            }
        });
        ((AbstractDocument) jTextFieldDecrementar.getDocument()).setDocumentFilter(new SoloFiltroNumerico());
        jPanel1.add(jTextFieldDecrementar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 110, 30));

        jPanelMesero.setBackground(new java.awt.Color(44, 44, 44));
        jPanelMesero.setRoundBottomLeft(15);
        jPanelMesero.setRoundBottomRight(15);
        jPanelMesero.setRoundTopLeft(15);
        jPanelMesero.setRoundTopRight(15);
        jPanelMesero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAceptar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAceptar.setText("Aceptar");
        jLabelAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAceptarMouseClicked(evt);
            }
        });
        jPanelMesero.add(jLabelAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel1.add(jPanelMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDecrementarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDecrementarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDecrementarActionPerformed

    private void jLabelAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAceptarMouseClicked

    }//GEN-LAST:event_jLabelAceptarMouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAceptar;
    private javax.swing.JLabel jLabelDecrementar;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JPanel jPanel1;
    private GUI.PanelRound jPanelMesero;
    private javax.swing.JTextField jTextFieldDecrementar;
    // End of variables declaration//GEN-END:variables
}
