package GUI;

import entidades.IngredienteProducto;
import entidades.Producto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author janot
 */
public class VentanaIngredientesDeProducto extends javax.swing.JDialog {
    private VentanaProductos ventana;
    Control control = new Control();
    /**
     * Creates new form VentanaIngredientesDeProducto
     */
    public VentanaIngredientesDeProducto(VentanaProductos ventana, boolean modal) {
        super(ventana, modal);
        this.ventana = ventana;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombreProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIngredientesProducto = new javax.swing.JTable();
        jLabelIconCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreProducto.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        jLabelNombreProducto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreProducto.setText("NO TIENE INGREDIENTES");
        jPanel1.add(jLabelNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 290, -1));

        jTableIngredientesProducto.setBackground(new java.awt.Color(255, 255, 255));
        jTableIngredientesProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Ingrediente", "Cantidad","Unidad de Medida"
            }
        ));
        jScrollPane1.setViewportView(jTableIngredientesProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 370, 280));

        jLabelIconCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cross-small.png"))); // NOI18N
        jLabelIconCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIconCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelIconCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelIconCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconCerrarMouseClicked
        control.cerrarDialogo(this);
    }//GEN-LAST:event_jLabelIconCerrarMouseClicked

    
    private void cargarDatos(){
        if(!ventana.ingredientesDeProducto.isEmpty()){
            jLabelNombreProducto.setText(ventana.ingredientesDeProducto.get(0).getProducto().getNombre());
        }
        DefaultTableModel model = (DefaultTableModel) jTableIngredientesProducto.getModel();
        model.setRowCount(0);
        for (IngredienteProducto ingrediente : ventana.ingredientesDeProducto) {
            model.addRow(new Object[]{
                ingrediente.getIngrediente().getNombre(),
                ingrediente.getCantidad(),
                ingrediente.getIngrediente().getUnidadMedida()
            });
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelIconCerrar;
    private javax.swing.JLabel jLabelNombreProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIngredientesProducto;
    // End of variables declaration//GEN-END:variables
}
