/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author janot
 */
public class VentanaMenuMesero extends javax.swing.JFrame {
    private Control control = new Control();
    
    /**
     * Creates new form VentanaMenuMesero
     */
    public VentanaMenuMesero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRestaurante = new javax.swing.JLabel();
        jPanelComandas = new javax.swing.JPanel();
        jLabelIconComanda = new javax.swing.JLabel();
        jPanelNuevaComanda = new javax.swing.JPanel();
        jLabelIconNuevaComanda = new javax.swing.JLabel();
        jPanelComandasPendientes = new javax.swing.JPanel();
        jLabelIconComandasPendientes = new javax.swing.JLabel();
        jLabelNuevaComanda = new javax.swing.JLabel();
        jLabelComandas1 = new javax.swing.JLabel();
        jLabelNuevaComanda1 = new javax.swing.JLabel();
        jLabelRegresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRestaurante.setFont(new java.awt.Font("Product Sans Infanity", 0, 66)); // NOI18N
        jLabelRestaurante.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRestaurante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRestaurante.setText("Restaurante");
        jPanel1.add(jLabelRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 370, -1));

        jPanelComandas.setBackground(new java.awt.Color(217, 217, 217));
        jPanelComandas.setForeground(new java.awt.Color(217, 217, 217));

        jLabelIconComanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/order-food-online.png"))); // NOI18N
        jLabelIconComanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIconComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconComandaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelComandasLayout = new javax.swing.GroupLayout(jPanelComandas);
        jPanelComandas.setLayout(jPanelComandasLayout);
        jPanelComandasLayout.setHorizontalGroup(
            jPanelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIconComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanelComandasLayout.setVerticalGroup(
            jPanelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIconComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelComandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 150, 140));

        jPanelNuevaComanda.setBackground(new java.awt.Color(217, 217, 217));
        jPanelNuevaComanda.setForeground(new java.awt.Color(217, 217, 217));

        jLabelIconNuevaComanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconNuevaComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/square-plus.png"))); // NOI18N
        jLabelIconNuevaComanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIconNuevaComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconNuevaComandaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelNuevaComandaLayout = new javax.swing.GroupLayout(jPanelNuevaComanda);
        jPanelNuevaComanda.setLayout(jPanelNuevaComandaLayout);
        jPanelNuevaComandaLayout.setHorizontalGroup(
            jPanelNuevaComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIconNuevaComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanelNuevaComandaLayout.setVerticalGroup(
            jPanelNuevaComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIconNuevaComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelNuevaComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        jPanelComandasPendientes.setBackground(new java.awt.Color(217, 217, 217));
        jPanelComandasPendientes.setForeground(new java.awt.Color(217, 217, 217));

        jLabelIconComandasPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconComandasPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pending.png"))); // NOI18N
        jLabelIconComandasPendientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIconComandasPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconComandasPendientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelComandasPendientesLayout = new javax.swing.GroupLayout(jPanelComandasPendientes);
        jPanelComandasPendientes.setLayout(jPanelComandasPendientesLayout);
        jPanelComandasPendientesLayout.setHorizontalGroup(
            jPanelComandasPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIconComandasPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanelComandasPendientesLayout.setVerticalGroup(
            jPanelComandasPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIconComandasPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelComandasPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        jLabelNuevaComanda.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNuevaComanda.setFont(new java.awt.Font("Product Sans Infanity", 1, 24)); // NOI18N
        jLabelNuevaComanda.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNuevaComanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNuevaComanda.setText("Comandas Pendientes");
        jPanel1.add(jLabelNuevaComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 320, 50));

        jLabelComandas1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelComandas1.setFont(new java.awt.Font("Product Sans Infanity", 1, 24)); // NOI18N
        jLabelComandas1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelComandas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelComandas1.setText("Comandas");
        jPanel1.add(jLabelComandas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 150, -1));

        jLabelNuevaComanda1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNuevaComanda1.setFont(new java.awt.Font("Product Sans Infanity", 1, 24)); // NOI18N
        jLabelNuevaComanda1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNuevaComanda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNuevaComanda1.setText("Nueva Comanda");
        jPanel1.add(jLabelNuevaComanda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 200, 50));

        jLabelRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow-small-left.png"))); // NOI18N
        jLabelRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelIconComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconComandaMouseClicked
        control.mostrarHistorialComandasConPermisosDeMesero();
        control.cerrarPantalla(this);
    }//GEN-LAST:event_jLabelIconComandaMouseClicked

    private void jLabelIconNuevaComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconNuevaComandaMouseClicked
        control.mostrarPantallaComandaNueva(this, rootPaneCheckingEnabled);
    }//GEN-LAST:event_jLabelIconNuevaComandaMouseClicked

    private void jLabelIconComandasPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconComandasPendientesMouseClicked
        control.mostrarHistorialComandasConPermisosDeMesero();
        control.cerrarPantalla(this);
    }//GEN-LAST:event_jLabelIconComandasPendientesMouseClicked

    private void jLabelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMouseClicked
        control.mostrarPantallaEscogerRol();
        control.cerrarPantalla(this);
    }//GEN-LAST:event_jLabelRegresarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelComandas1;
    private javax.swing.JLabel jLabelIconComanda;
    private javax.swing.JLabel jLabelIconComandasPendientes;
    private javax.swing.JLabel jLabelIconNuevaComanda;
    private javax.swing.JLabel jLabelNuevaComanda;
    private javax.swing.JLabel jLabelNuevaComanda1;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelRestaurante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelComandas;
    private javax.swing.JPanel jPanelComandasPendientes;
    private javax.swing.JPanel jPanelNuevaComanda;
    // End of variables declaration//GEN-END:variables
}
