package GUI;

/**
 *
 * @author janot
 */
public class VentanaHistorialComandas extends javax.swing.JFrame {
    Control control = new Control();
    
    /**
     * Creates new form VentanaHistorialComandas
     */
    public VentanaHistorialComandas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelComandas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelHistorialComandas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelIconFiltro = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelEstado1 = new javax.swing.JLabel();
        jLabelFechaHasta = new javax.swing.JLabel();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        dateTimePicker2 = new com.github.lgooddatepicker.components.DateTimePicker();
        jPanelFiltro = new GUI.PanelRound();
        jLabelFiltrar = new javax.swing.JLabel();
        jLabelIconPdf = new javax.swing.JLabel();
        jLabelFechaDesde = new javax.swing.JLabel();
        jLabelReporte = new javax.swing.JLabel();
        jPanelQuitarFiltro = new GUI.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabelGenerar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow-small-left.png"))); // NOI18N
        jLabelRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelComandas.setFont(new java.awt.Font("Product Sans Infanity", 1, 66)); // NOI18N
        jLabelComandas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelComandas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelComandas.setText("Comandas");
        jPanel1.add(jLabelComandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(69, 71, 75));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHistorialComandas.setFont(new java.awt.Font("Product Sans Infanity", 1, 24)); // NOI18N
        jLabelHistorialComandas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHistorialComandas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHistorialComandas.setText("Historial de Comandas");
        jPanel2.add(jLabelHistorialComandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 320, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 920, 40));

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/filter.png"))); // NOI18N
        jPanel3.add(jLabelIconFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Abiertas", "Entregadas", "Canceladas" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 80, 30));

        jLabelEstado1.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelEstado1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstado1.setText("Estado:");
        jPanel3.add(jLabelEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabelFechaHasta.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelFechaHasta.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFechaHasta.setText("Fecha Hasta:");
        jPanel3.add(jLabelFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, 20));
        jPanel3.add(dateTimePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));
        jPanel3.add(dateTimePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jPanelFiltro.setBackground(new java.awt.Color(44, 44, 44));
        jPanelFiltro.setRoundBottomLeft(15);
        jPanelFiltro.setRoundBottomRight(15);
        jPanelFiltro.setRoundTopLeft(15);
        jPanelFiltro.setRoundTopRight(15);
        jPanelFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFiltrar.setFont(new java.awt.Font("Product Sans Infanity", 1, 14)); // NOI18N
        jLabelFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFiltrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFiltrar.setText("Filtrar");
        jLabelFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelFiltro.add(jLabelFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jPanel3.add(jPanelFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 100, 20));

        jLabelIconPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/file-pdf.png"))); // NOI18N
        jLabelIconPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelIconPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, 40));

        jLabelFechaDesde.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelFechaDesde.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFechaDesde.setText("Fecha Desde:");
        jPanel3.add(jLabelFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 20));

        jLabelReporte.setText("Reporte");
        jLabelReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelReporte.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        jLabelReporte.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jLabelReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, 20));

        jPanelQuitarFiltro.setBackground(new java.awt.Color(44, 44, 44));
        jPanelQuitarFiltro.setRoundBottomLeft(15);
        jPanelQuitarFiltro.setRoundBottomRight(15);
        jPanelQuitarFiltro.setRoundTopLeft(15);
        jPanelQuitarFiltro.setRoundTopRight(15);
        jPanelQuitarFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Product Sans Infanity", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quitar Filtro");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQuitarFiltro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jPanel3.add(jPanelQuitarFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 100, 20));

        jLabelGenerar.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        jLabelGenerar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGenerar.setText("Generar");
        jLabelGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 920, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Folio", "Fecha", "Mesa", "Total", "Cliente", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 920, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMouseClicked
        control.mostrarPantallaMenuAdmin();
        control.cerrarPantalla(this);
    }//GEN-LAST:event_jLabelRegresarMouseClicked


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelComandas;
    private javax.swing.JLabel jLabelEstado1;
    private javax.swing.JLabel jLabelFechaDesde;
    private javax.swing.JLabel jLabelFechaHasta;
    private javax.swing.JLabel jLabelFiltrar;
    private javax.swing.JLabel jLabelGenerar;
    private javax.swing.JLabel jLabelHistorialComandas;
    private javax.swing.JLabel jLabelIconFiltro;
    private javax.swing.JLabel jLabelIconPdf;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private GUI.PanelRound jPanelFiltro;
    private GUI.PanelRound jPanelQuitarFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
