package GUI;

import DTOs.ProductoComandaDTO;
import entidades.Producto;
import excepciones.NegocioException;
import interfaces.IProductoBO;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import manejadoresDeObjetoNegocio.ManejadorObjetosNegocio;
import utils.SoloEnterosFilter;

/**
 *
 * @author janot
 */
public class VentanaAgregarProductoAComanda extends javax.swing.JDialog {
    private Control control = new Control();
    private IProductoBO productoBO;
    private List<Producto> productosHabilitados;
    private ProductoComandaDTO productoComandaDTO;
    private VentanaComandaNueva ventana;
    
    /**
     * Creates new form VentanaAgregarProductoAComanda
     */
    public VentanaAgregarProductoAComanda(VentanaComandaNueva ventana, boolean modal) {
        super(ventana, modal);
        productoBO = ManejadorObjetosNegocio.crearProductoBO();
        this.ventana = ventana;
        initComponents();
        asignarDatosListaproductosHabilitados();
        cargarjListProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDinero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelComentario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList<>();
        jTextFieldProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaComentario = new javax.swing.JTextArea();
        jLabelCantidad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jPanelCancelar = new GUI.PanelRound();
        jLabelCancelar = new javax.swing.JLabel();
        jPanelAgregar = new GUI.PanelRound();
        jLabelAgregar = new javax.swing.JLabel();
        jLabelComentario1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDinero.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        jLabelDinero.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDinero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDinero.setText("$");
        jPanel1.add(jLabelDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 200, -1));

        jLabel2.setFont(new java.awt.Font("Product Sans Infanity", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jTextFieldCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCantidad.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                calcularTotal();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                jLabelDinero.setText("$");

            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                // Este se usa con estilos en JTextPane, no aplica en JTextField
            }

        });

        ((AbstractDocument) jTextFieldCantidad.getDocument()).setDocumentFilter(new SoloEnterosFilter());
        jPanel1.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 190, 30));

        jLabelComentario.setFont(new java.awt.Font("Product Sans Infanity", 0, 12)); // NOI18N
        jLabelComentario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelComentario.setText("*Opcional");
        jPanel1.add(jLabelComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 365, -1, -1));

        jListProductos.setBackground(new java.awt.Color(255, 255, 255));
        jListProductos.setFont(new java.awt.Font("Product Sans Infanity", 0, 14)); // NOI18N
        jListProductos.setForeground(new java.awt.Color(0, 0, 0));
        jListProductos.setModel(new DefaultListModel<>());
        jListProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListProductosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 190, 130));

        jTextFieldProducto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductoActionPerformed(evt);
            }
        });
        jTextFieldProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 190, 30));

        jLabel4.setFont(new java.awt.Font("Product Sans Infanity", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Producto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jTextAreaComentario.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaComentario.setColumns(15);
        jTextAreaComentario.setRows(3);
        jScrollPane2.setViewportView(jTextAreaComentario);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 190, 70));

        jLabelCantidad.setFont(new java.awt.Font("Product Sans Infanity", 0, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantidad.setText("Cantidad");
        jPanel1.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Product Sans Infanity", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Producto");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, -1));

        jLabelTotal.setFont(new java.awt.Font("Product Sans Infanity", 1, 24)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal.setText("Total:");
        jPanel1.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 70, -1));

        jPanelCancelar.setBackground(new java.awt.Color(44, 44, 44));
        jPanelCancelar.setRoundBottomLeft(15);
        jPanelCancelar.setRoundBottomRight(15);
        jPanelCancelar.setRoundTopLeft(15);
        jPanelCancelar.setRoundTopRight(15);
        jPanelCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCancelar.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        jLabelCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancelar.setText("Cancelar");
        jLabelCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelarMouseClicked(evt);
            }
        });
        jPanelCancelar.add(jLabelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jPanel1.add(jPanelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 90, 30));

        jPanelAgregar.setBackground(new java.awt.Color(44, 44, 44));
        jPanelAgregar.setRoundBottomLeft(15);
        jPanelAgregar.setRoundBottomRight(15);
        jPanelAgregar.setRoundTopLeft(15);
        jPanelAgregar.setRoundTopRight(15);
        jPanelAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAgregar.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        jLabelAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregar.setText("Agregar");
        jLabelAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarMouseClicked(evt);
            }
        });
        jPanelAgregar.add(jLabelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jPanel1.add(jPanelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 90, 30));

        jLabelComentario1.setFont(new java.awt.Font("Product Sans Infanity", 0, 14)); // NOI18N
        jLabelComentario1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelComentario1.setText("Comentario");
        jPanel1.add(jLabelComentario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductoKeyTyped
        String busqueda = jTextFieldProducto.getText();
        buscador(busqueda);
    }//GEN-LAST:event_jTextFieldProductoKeyTyped

    private void jListProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListProductosValueChanged
        if (jListProductos.getSelectedValue() != null) {
            jTextFieldProducto.setText(jListProductos.getSelectedValue().toString());
            jTextFieldCantidad.setText("1");
        }
    }//GEN-LAST:event_jListProductosValueChanged

    private void jLabelAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarMouseClicked
        agregarProductoAComanda();

    }//GEN-LAST:event_jLabelAgregarMouseClicked

    private void jLabelCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarMouseClicked
        control.cerrarDialogo(this);
    }//GEN-LAST:event_jLabelCancelarMouseClicked

    private void jTextFieldProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductoActionPerformed

    
    /*UTILS*/
    public void asignarDatosListaproductosHabilitados(){
        try {
            this.productosHabilitados = productoBO.consultarProductosHabilitados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }
    
    public void cargarjListProductos(){
        DefaultListModel<Producto> modeloProductos = new DefaultListModel<>();
        jListProductos.setModel(modeloProductos);
        
        for (Producto producto : productosHabilitados) {
            modeloProductos.addElement(producto);
        }
    }
    
    public void buscador(String busqueda){
        List<Producto> productosFiltrados = productosHabilitados.stream()
                                                                .filter(producto -> producto.getNombre().trim().toLowerCase().startsWith(busqueda.toLowerCase().trim()))
                                                                .collect(Collectors.toList());
        DefaultListModel<Producto> modeloProductos = new DefaultListModel<>();
        jListProductos.setModel(modeloProductos);
        
        for (Producto producto : productosFiltrados) {
            modeloProductos.addElement(producto);
        }
    }
    
    public void calcularTotal(){
        if(jListProductos.getSelectedValue() != null && !jTextFieldCantidad.getText().trim().isEmpty()){
            jLabelDinero.setText("$");
            double precioProducto = jListProductos.getSelectedValue().getPrecio();
            int cantidad = Integer.parseInt(jTextFieldCantidad.getText());
            double total = precioProducto * cantidad;
            jLabelDinero.setText(jLabelDinero.getText() + total);
        }
    }
    
    public void agregarProductoAComanda(){
        if(jListProductos.getSelectedValue() == null){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un Producto");
        }
        
        if(jTextFieldCantidad.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "La cantidad esta vacia");
        }
        else if(Integer.parseInt(jTextFieldCantidad.getText()) <= 0 || jTextFieldCantidad.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "La cantidad no puede ser 0, menor a cero ,o estar vacia");
        }
        else if(jListProductos.getSelectedValue() != null){
            Producto producto = jListProductos.getSelectedValue();
            double precioActual = producto.getPrecio();
            String comentario = jTextAreaComentario.getText();
            Integer cantidad = Integer.parseInt(jTextFieldCantidad.getText());
            double importe = precioActual * cantidad;
            
            productoComandaDTO = new ProductoComandaDTO(producto, precioActual, comentario, cantidad, importe);
            
            ventana.productosComandaDTO.add(productoComandaDTO);
            ventana.cargarDatosTabla();
            control.cerrarDialogo(this);
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAgregar;
    private javax.swing.JLabel jLabelCancelar;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelComentario;
    private javax.swing.JLabel jLabelComentario1;
    private javax.swing.JLabel jLabelDinero;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JList<Producto> jListProductos;
    private javax.swing.JPanel jPanel1;
    private GUI.PanelRound jPanelAgregar;
    private GUI.PanelRound jPanelCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaComentario;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldProducto;
    // End of variables declaration//GEN-END:variables
}
