/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author janot
 */
public class VentanaEscogerRol extends javax.swing.JFrame {
    private Control control = new Control();
    
    /**
     * Creates new form ventanaEscogerRol
     */
    public VentanaEscogerRol() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelAdmin = new GUI.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        JLabelTitulo = new javax.swing.JLabel();
        jPanelMe = new GUI.PanelRound();
        jLabelMesero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAdmin.setBackground(new java.awt.Color(44, 44, 44));
        jPanelAdmin.setRoundBottomLeft(15);
        jPanelAdmin.setRoundBottomRight(15);
        jPanelAdmin.setRoundTopLeft(15);
        jPanelAdmin.setRoundTopRight(15);
        jPanelAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Soy Administrador");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanelAdmin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 60));

        jPanel1.add(jPanelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 310, 60));

        JLabelTitulo.setFont(new java.awt.Font("Product Sans Infanity", 0, 48)); // NOI18N
        JLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        JLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelTitulo.setText("INICIO");
        jPanel1.add(JLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 640, 60));

        jPanelMe.setBackground(new java.awt.Color(44, 44, 44));
        jPanelMe.setRoundBottomLeft(15);
        jPanelMe.setRoundBottomRight(15);
        jPanelMe.setRoundTopLeft(15);
        jPanelMe.setRoundTopRight(15);
        jPanelMe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMesero.setFont(new java.awt.Font("Product Sans Infanity", 0, 36)); // NOI18N
        jLabelMesero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMesero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesero.setText("Soy Mesero");
        jPanelMe.add(jLabelMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 60));

        jPanel1.add(jPanelMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 310, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        control.mostrarPantallaMenuAdmin();
        control.cerrarPantalla(this);
    }//GEN-LAST:event_jLabel1MouseClicked

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMesero;
    private javax.swing.JPanel jPanel1;
    private GUI.PanelRound jPanelAdmin;
    private GUI.PanelRound jPanelMe;
    // End of variables declaration//GEN-END:variables
}
