/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author janot
 */
public class VentanaProductos extends javax.swing.JFrame {
    Control control = new Control();
    
    /**
     * Creates new form VentanaProductos
     */
    public VentanaProductos() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelProductos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelProductosDelMenu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelIconFiltro = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelProductoNuevo2 = new javax.swing.JLabel();
        jPanelFiltro = new GUI.PanelRound();
        jLabelFiltrar = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jPanelBuscar = new GUI.PanelRound();
        jLabelBuscar = new javax.swing.JLabel();
        jLabelEstado3 = new javax.swing.JLabel();
        jLabelProductoNuevo1 = new javax.swing.JLabel();
        jLabelIconProductoNuevo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelFiltrar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow-small-left.png"))); // NOI18N
        jLabelRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductos.setText("Productos");
        jLabelProductos.setFont(new java.awt.Font("Product Sans Infanity", 1, 66)); // NOI18N
        jLabelProductos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(69, 71, 75));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProductosDelMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProductosDelMenu.setText("Productos del Menu");
        jLabelProductosDelMenu.setFont(new java.awt.Font("Product Sans Infanity", 1, 24)); // NOI18N
        jLabelProductosDelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabelProductosDelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 320, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 920, 40));

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/filter.png"))); // NOI18N
        jPanel3.add(jLabelIconFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Todo","Platillo", "Bebida", "Postre" }));
        jComboBoxCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, 30));

        jLabelProductoNuevo2.setText("Nuevo");
        jLabelProductoNuevo2.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        jLabelProductoNuevo2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jLabelProductoNuevo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jPanelFiltro.setBackground(new java.awt.Color(44, 44, 44));
        jPanelFiltro.setRoundBottomLeft(15);
        jPanelFiltro.setRoundBottomRight(15);
        jPanelFiltro.setRoundTopLeft(15);
        jPanelFiltro.setRoundTopRight(15);
        jPanelFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFiltrar.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        jLabelFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFiltrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFiltrar.setText("Filtrar");
        jLabelFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelFiltro.add(jLabelFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel3.add(jPanelFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 100, 30));

        jLabelCategoria.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCategoria.setText("Categoria:");
        jPanel3.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTextFieldBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 150, 30));

        jPanelBuscar.setBackground(new java.awt.Color(44, 44, 44));
        jPanelBuscar.setRoundBottomLeft(15);
        jPanelBuscar.setRoundBottomRight(15);
        jPanelBuscar.setRoundTopLeft(15);
        jPanelBuscar.setRoundTopRight(15);
        jPanelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBuscar.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        jLabelBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscar.setText("Buscar");
        jLabelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBuscar.add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel3.add(jPanelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 100, 30));

        jLabelEstado3.setText("Buscar:");
        jLabelEstado3.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        jLabelEstado3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jLabelEstado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabelProductoNuevo1.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        jLabelProductoNuevo1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelProductoNuevo1.setText("Producto");
        jPanel3.add(jLabelProductoNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jLabelIconProductoNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconProductoNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jLabelIconProductoNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelIconProductoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 920, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Precio", "Tipo", "Ingredientes", "Modificar", "Eliminar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 920, 370));

        jLabelFiltrar2.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        jLabelFiltrar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFiltrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFiltrar2.setText("Filtrar");
        jLabelFiltrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelFiltrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMouseClicked
        control.mostrarPantallaMenuAdmin();
        control.cerrarPantalla(this);
    }//GEN-LAST:event_jLabelRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelEstado3;
    private javax.swing.JLabel jLabelFiltrar;
    private javax.swing.JLabel jLabelFiltrar2;
    private javax.swing.JLabel jLabelIconFiltro;
    private javax.swing.JLabel jLabelIconProductoNuevo;
    private javax.swing.JLabel jLabelProductoNuevo1;
    private javax.swing.JLabel jLabelProductoNuevo2;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JLabel jLabelProductosDelMenu;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private GUI.PanelRound jPanelBuscar;
    private GUI.PanelRound jPanelFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
